service: qilin-lambda-advance-2

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  region: ap-southeast-1
  role: arn:aws:iam::494526681395:role/for-aws-training-2
  timeout: 30
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'lambda:InvokeFunction'
      Resource: ''
package:
  artifact: target/qilin-lambda-advance-2.jar

#resources:
#  Resources:
#    qilinAdvanceTopic:
#      Type: AWS::SNS::Topic
#      Properties:
#        TopicName: qilinAdvanceTopic

functions:
  currentTime:
    handler: com.serverless.Handler
    events:
      - sns: qilinAdvanceTopic
#    events:
#      - http:
#          path: ping
#          method: get
