service: qilin-lambda-basic-5

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  region: ap-southeast-1
  role: arn:aws:iam::494526681395:role/for-aws-training-2
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:*Object'
      Resource: arn:aws:s3:::qilin-lambda-basic-4-bucket
    - Effect: 'Allow'
      Action:
        - 's3:*Object'
      Resource: arn:aws:s3:::qilin-lambda-basic-5-bucket


package:
  artifact: target/qilin-lambda-basic-5.jar

functions:
  currentTime:
    handler: com.serverless.Handler
#    events:
#      - http:
#          path: ping
#          method: get
